<?php
class model_HTAccess extends model_File
{
	private $public;

	private $authType;
	private $authName;
	private $require;

	public function __construct( $repositoryPath )
	{
		parent::__construct( $repositoryPath . '/' . '.htaccess' );
		$this->parse( );
	}

	public function load( $path = false )
	{
		parent::load( $path );
		$this->parse( );
	}

	public function save( )
	{
		$this->clearContents( );
		$this->addHeader( );
		$this->addAuthTypeName( );
		$this->addLimitRequire( );
	}

	public function setAuthType( $authType )
	{
		// $this->authType = $authType;
	}
	public function getAuthType( )
	{
		return $this->authType;
	}
	
	public function setAuthName( $authName )
	{
		$this->authName = $authName;
	}
	public function getAuthName( )
	{
		return $this->authName;
	}

	public function setPublic( $public )
	{
		$this->public = $public;
	}
	public function getPublic( $public )
	{
		return $this->public;
	}

	private function addHeader( )
	{
		$this->addContents( '# .htaccess file autogenerated by phpSVNAdmin v' . $cfg[ 'APP_VERSION' ] );
	}

	private function addAuthTypeName( )
	{
		$this->addContents( 'AuthType	Basic' );
		$this->addContents( 'AuthName	"' . $this->authName . '"' );
	}

	private function addLimitRequire( )
	{
		if ( $this->public )
			$this->addContents( '<LimitExcept GET PROPFIND OPTIONS REPORT>' );
		$this->addContents( 'Require	' . implode( ' ', $this->require ) );
		if ( $this->public )
			$this->addContents( '</LimitExcept>' );
	}
}
?>